---
- name: Start  instances
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'i-XXXXXXXX'
    region: ap-southeast-1
  tasks:
    - name: Start the feature instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: running
        wait: True
---
- hosts: myserver
  remote_user: ubuntu
  tasks:
  - name: Gather facts
    action: ec2_facts

  - name: Stop myserver instance
    local_action:
        module: ec2
        region: "ap-southeast-1"
        instance_ids: "{{ansible_ec2_instance_id}}"
        state: stopped